# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u73ed\u7ea7')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='\u8003\u8bd5\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u8003\u8bd5',
                'verbose_name_plural': '\u8003\u8bd5',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5e74\u7ea7')),
            ],
            options={
                'verbose_name': '\u5e74\u7ea7',
                'verbose_name_plural': '\u5e74\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='RawScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, verbose_name='\u8003\u53f7')),
                ('student_name', models.CharField(max_length=32, verbose_name='\u59d3\u540d')),
                ('chinese', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u8bed\u6587\u6210\u7ee9')),
                ('mathematics', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u6570\u5b66\u6210\u7ee9')),
                ('english', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u82f1\u8bed\u6210\u7ee9')),
                ('physics', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u7269\u7406\u6210\u7ee9')),
                ('chemistry', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u5316\u5b66\u6210\u7ee9')),
                ('biology', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u751f\u7269\u6210\u7ee9')),
                ('politics', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u653f\u6cbb\u6210\u7ee9')),
                ('history', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u5386\u53f2\u6210\u7ee9')),
                ('geography', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='\u5730\u7406\u6210\u7ee9')),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Exam')),
            ],
            options={
                'verbose_name': '\u539f\u59cb\u6210\u7ee9',
                'verbose_name_plural': '\u539f\u59cb\u6210\u7ee9',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5b66\u6821')),
            ],
            options={
                'verbose_name': '\u5b66\u6821',
                'verbose_name_plural': '\u5b66\u6821',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Grade'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.School'),
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Grade'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.School'),
        ),
    ]
