# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawscore',
            name='imp_datetime',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 9, 49, 6, 449056, tzinfo=utc), verbose_name='\u5bfc\u5165\u65e5\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='biology',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u751f\u7269\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='chemistry',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u5316\u5b66\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='chinese',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u8bed\u6587\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='english',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u82f1\u8bed\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='geography',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u5730\u7406\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='history',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u5386\u53f2\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='mathematics',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u6570\u5b66\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='physics',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u7269\u7406\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='rawscore',
            name='politics',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='\u653f\u6cbb\u6210\u7ee9'),
        ),
    ]
