# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20170523_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawscore',
            name='imp_datetime',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 9, 50, 48, 45231, tzinfo=utc), verbose_name='\u5bfc\u5165\u65e5\u65f6\u95f4'),
        ),
    ]
